### ISSUE TITLE
Configurable Security Policies vs Runtime Policies and Agent vs Server Concerns

### ISSUE THREAD

**Issue by avanderhoorn** [Glimpse/Glimpse.Prototype#4]
Currently Security Policies are just one type/implementation of a Runtime Policy. Specifically, one can create a Runtime Policy that has nothing to do with securing/limiting access to Glimpse or they can create a policy which simply controls what assets Glimpse will profile. This lack of a clear distinction isn't a problem for those who are explicitly aware of the different, but for those who aren't this can lead to inadvertent gaps in security. What's more, with the inception of the Agent/Server model, an argument could be made that the concerns for the Agent are very different to those of the Server. Hence the following is the design outline for how Agent/Server Security/Policies will operate and how Agents will authenticate with the server (the latter will probably be split out into a different issues).

**Agent:**
- Policies *(required)* - To control what requests are profiled
- Security *(not required)* - No assets are severed through the agent 

**Server:**
- Policies *(not required)* - Not needed as the server doesn't control what requests are profiled
- Security *(required)* - To control who can access the various endpoints/data

*... work in progress*

**Comment by nikmd23** [comment]
This is being addressed in #40.
